
export const START_GAME_SUCCESS = 'START_GAME_SUCCESS';

export const START_MATCH = 'START_MATCH';
export const START_MATCH_SUCCESS = 'START_MATCH_SUCCESS';
export const START_MATCH_FAILED = 'START_MATCH_FAILED';
export const DISCARD_ROUND_START = 'DISCARD_ROUND_START';
export const DISCARD_ROUND_SUCCESS = 'DISCARD_ROUND_SUCCESS';
export const DISCARD_ROUND_FAILED = 'DISCARD_ROUND_FAILED';

export const PLAY_CARD_START = 'PLAY_CARD_START';
export const PLAY_CARD_SUCCESS = 'PLAY_CARD_SUCCESS';
export const PLAY_CARD_FAILED = 'PLAY_CARD_FAILED';

export const PLAYED_CARD_START = 'PLAYED_CARD_START';
export const PLAYED_CARD_SUCCESS = 'PLAYED_CARD_SUCCESS';
export const PLAYED_CARD_FAILED = 'PLAYED_CARD_FAILED';

export const ANOTHER_MATCH_START = 'ANOTHER_MATCH_START';
export const ANOTHER_MATCH_SUCCESS = 'ANOTHER_MATCH_SUCCESS';
export const NEW_MATCH = 'NEW_MATCH';

export const NEW_DECK = 'NEW_DECK';
export const NEW_DECK_INIT = 'NEW_DECK_INIT';
export const NEW_DECK_START = 'NEW_DECK_START';
export const NEW_DECK_SUCCESS = 'NEW_DECK_SUCCESS';
export const NEW_DECK_FAILED = 'NEW_DECK_FAILED';
export const PLAYER_DRAW_CARD_START = 'PLAYER_DRAW_CARD_START';
export const PLAYER_DRAW_CARD_SUCCESS = 'PLAYER_DRAW_CARD_SUCCESS';
export const CREATE_PLAYERS_START = 'CREATE_PLAYERS_START';
export const CREATE_PLAYERS_SUCCESS = 'CREATE_PLAYERS_SUCCESS';
export const CREATE_PLAYERS_FAILED = 'CREATE_PLAYERS_FAILED';

